(function () {
   'use strict';

   angular
      .module('ucroo', [
         // third part modules
         'ngCookies',
         'ngSanitize',
         'ui.router',
         'ngAnimate',
         'ngDialog',
         'ui.select',
         'permission',
         'ui.calendar',
         'angular.filter',
         'datePicker',
         'jkuri.gallery',
         'monospaced.elastic',

         // third part directives
         'ngDropdowns',
         'ngFileUpload',
         'infinite-scroll',

         // services
         'api',
         'user',
         'alerts',
         'dataShare',

         // modules
         'helper',
         'calendarTimeline',
         'createClub',
         'animateMargin',
         'clickOutside',
         'messagesPopup',
         'notificationPopup',
         'header',
         'mainMenu',
         'atUniversity',
         'classOnBodyDirective',
         'rhsUsersList',
         'invite',
         'passwordsMatch',
         'footer',
         'timer',
         'comments',
         'dropdown',
         'keySubmit',
         'postSummary',
         'newFeed',
         'feedTypes',
         'datePickerEx',
         'fileList',
         'feedList',
         'selectUser',
         'selectUserList',
         'eventList',
         'redirect',
         'loader',
         'fieldsList',
         'importCSV',
         'infiniteScrollUp',
         'message',
         'ucrTypeahead',
         'userGallery',
         'marketplace',
         'comboWithCheckboxes',

         // views
         'recentActivity',
         'universityFeeds',
         'profile',
         'groups',
         'profileConnections',
         'calendar',
         'about',
         'subjects',
         'editProfile',
         'news',
         'newsDetails',
         'newsList',
         'messages',
         'conversationList',
         'conversation',
         'groupView',
         'clubsSuggestions',
         'clubs',
         'club',
         'createClub',
         'clubsList',
         'clubFeed',
         'club',
         'discussion',
         'events',
         'clubsEvents',
         'studyTimer',
         'notifications',

         'clubInfo',
         'createClub',
         'mentorGroups',
         'customGroup',
         'groupList',
         'suggestions',
         'main',
         'login',
         'passwordRecovery',
         'landing',
         'footer',
         'external',
         'signUp',
         'stepOne',
         'stepTwo',
         'stepThree',
         'customgroups',
         'newMessage',
         'connections',
         'connectionsList',
         'connectionsSuggestions',
         'connectionsRequests',
         'ucrAccount',
         'uCalendar',
         'ucrAccountPrivacy',
         'ucrAccountNotification',
         'ucrAccountBlock',
         'ucrAccountOther'

      ]);

})();
